apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dtonedemo-app
  name: dtonedemo-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dtonedemo-app
  template:
    metadata:
      labels:
        app: dtonedemo-app
    spec:
      containers:
        - image: index.docker.io/captainfaizalkirk/dtone-trial
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 30
          name: dtonedemo-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dtonedemo-app-service
spec:
  ports:
    - nodePort: 30101
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dtonedemo-app
  type: NodePort

